### PR TITLE
WIP: add initial SlowTemplatePeriodogram class

### PR DESCRIPTION
**Pull request by jakevdp**
I noticed that in the new model tests, there's a whole lot of functionality that essentially computes a slow periodogram by direct grid-search minimization.

I think it's cleaner to instead have an interface in the package itself that computes this. Here's my initial attempt at a ``SlowTemplatePeriodogram``, with an API similar to ``astropy.stats.LombScargle``.

This is a work in progress (WIP), so please don't merge yet, but I wanted to get your thoughts on this. Once we feel like this is in pretty good shape, we can work on a new version of the Fast periodogram that should produce the same output to within optimization errors. This leads to a really natural and concise way to test the main method.

Example usage:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

from pyftp.template import Template
from pyftp.slow_template_periodogram import SlowTemplatePeriodogram
```

```python
def generate_template(nharmonics, rseed=0):
    rng = np.random.RandomState(rseed)
    c_n, s_n = rng.randn(2, nharmonics) * 1. / np.arange(1, nharmonics + 1)
    return Template(c_n, s_n)

def generate_data(template, N, tmin, tmax, freq, dy=0.1, phase=0, amp=1, offset=10, rseed=0):
    rng = np.random.RandomState(rseed)
    t = tmin + (tmax - tmin) * np.random.rand(N)
    y = offset + amp * template(t * freq - phase) + dy * rng.randn(N)
    return t, y, dy
```

```python
fig, ax = plt.subplots(1, 2, figsize=(12, 4))

template = generate_template(4)
t_grid = np.linspace(0, 1, 1000)
ax[0].plot(t_grid, template(t_grid))

t, y, dy = generate_data(template, 100, 0, 100, freq=0.1, dy=0.5)
ax[1].errorbar(t, y, dy, fmt='.k', ecolor='gray', capsize=0);
```
gaeuunwdpndjswsiiiiiopbltfijiiiiiiltmskmiiiiopdhpjiiiiiiqh6tyiiiiiikeuykiyiiicjkmskmiiiiopdhpjiiiiiiqh6tyiiiiiikef8frab4carjctsaaaaasuvork5cyii

```python
stp = SlowTemplatePeriodogram(t, y, dy, template)
freq = np.linspace(0.01, 1.0, 500)

plt.plot(freq, stp.power(freq))
plt.ylim(0, 1);
```
b2o52btugrxsaaaaaelftksuqmcc

### CODE REVIEW

**Comment by jakevdp** [comment]
Here's some example usage:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

from pyftp.template import Template
from pyftp.slow_modeler import SlowTemplatePeriodogram
```

```python
def generate_template(nharmonics, rseed=0):
    rng = np.random.RandomState(rseed)
    c_n, s_n = rng.randn(2, nharmonics) * 1. / np.arange(1, nharmonics + 1)
    return Template(c_n, s_n)

def generate_data(template, N, tmin, tmax, freq, dy=0.1, phase=0, amp=1, offset=10, rseed=0):
    rng = np.random.RandomState(rseed)
    t = tmin + (tmax - tmin) * np.random.rand(N)
    y = offset + amp * template(t * freq - phase) + dy * rng.randn(N)
    return t, y, dy
```

```python
fig, ax = plt.subplots(1, 2, figsize=(12, 4))

template = generate_template(4)
t_grid = np.linspace(0, 1, 1000)
ax[0].plot(t_grid, template(t_grid))

t, y, dy = generate_data(template, 100, 0, 100, freq=0.1, dy=0.5)
ax[1].errorbar(t, y, dy, fmt='.k', ecolor='gray', capsize=0);
```
gaeuunwdpndjswsiiiiiopbltfijiiiiiiltmskmiiiiopdhpjiiiiiiqh6tyiiiiiikeuykiyiiicjkmskmiiiiopdhpjiiiiiiqh6tyiiiiiikef8frab4carjctsaaaaasuvork5cyii

```python
stp = SlowTemplatePeriodogram(t, y, dy, template)
freq = np.linspace(0.01, 1.0, 500)

plt.plot(freq, stp.power(freq))
plt.ylim(0, 1);
```
b2o52btugrxsaaaaaelftksuqmcc

**Comment by jakevdp** [comment]
sorry – the unused imports commit should have gone straight to master. Not part of this PR.

**Comment by jakevdp** [comment]
I think this is ready to merge now if you're happy with it.

**Comment by jakevdp** [comment]
So I've been testing this versus the fast template method. I expect the slow method to sometimes give suboptimal results, but it should *always* give a lower-bound to the true power (because you can't arrive at a chi-square that is smaller than the true minimum)

I'm finding, though, that there are many cases where the fast method gives an answer smaller than the slow method (by up to about ~0.5), which indicates that the fast method is not finding the correct periodogram value.

We should make sure to try and understand (and perhaps fix) the sources of these failures.

**Comment by johnh2o2** [comment]
Hi Jake,

This looks good, however I am myself working on a large update to the API which includes an implementation of the "slow" periodogram (via a `direct_summations` function); I will take a closer look at this and give you some comments but just wanted to give you a heads up and let you know that I am taking a look at this.

I did see some strange discrepancies between the slow/fast template periodogram myself, and that is something I agree that we should take seriously and resolve. I've just gotten a chance to sit down from this morning, so I'll look through what you've written and let you know my thoughts in a few minutes

Thanks!

John

**Comment by jakevdp** [comment]
Sounds good! Regarding the direct-summations – that's a slightly different beast, right? If I understand correctly, that's using the periodogram based on root finding, but computing relevant quantities directly rather than with the NFFT, yes?

If that's the case, this code is yet another useful check to have, because it doesn't rely on the root-finding approach at all.

**Comment by johnh2o2** [comment]
Hi Jake,

Oh I see what you're saying, that's a good idea; if I understand correctly, this is essentially the same as the gatspy template modeler, no? Or am I missing some subtleties? Either way, I agree it's good to have another implementation that is independent of the root finding to test against.

John

**Comment by jakevdp** [comment]
> his is essentially the same as the gatspy template modeler, no?

Yes, basically the same, except that it's built on the ``Template`` class defined here, so it's easier to compare directly with the other methods here.

Another difference is that gatspy does an iterative minimization across all parameters, while this does a minimization across just the phase, with a direct solution of the other parameters at each step (which is probably faster and more accurate, though I haven't done any benchmarks)

**Comment by jakevdp** [comment]
I just looked again at the Gatspy code: another difference is that it uses interpolation in the template evaluation. This method, because it's built on a Fourier-expanded template, uses direct evaluation of the template. Again, I suspect this leads to faster results, but I haven't done the benchmarks.

**Comment by jakevdp** [comment]
Quick question on this @johnh2o2 – is this code basically obsolete given your recent commits?

**Comment by jakevdp** [comment]
Added in 4c5a0141ebabd1e71c4db69d06e51b4d6c473d2f

**Pull request closed without merging**
