### PR TITLE
WIP: re-designed template class

### PR DESCRIPTION
**Pull request by jakevdp**
@johnh2o2 – I did a little re-design of the template class. Key features are splitting the alternate constructor into a class method, and adding unit tests to make sure everything is behaving properly.

Some functionality is still missing, but I thought I'd run this by you. Do you think this design makes sense? Do you see any issues with incorporating it into the package, once the additional features are in place?

### CODE REVIEW

**Comment by johnh2o2** [comment]
Great! This looks much simpler and makes more sense than what was there before. I agree with having a single way to instantiate the Template class (i.e. just `c_n` and `s_n`) and making the template callable is excellent. Let me know if there's anything on my end I can do that would be helpful. I'm just revising the paper and working on the proceedings at the moment.

**Comment by jakevdp** [comment]
Awesome – I'll try to understand a bit more what the old template class is doing, and add the necessary features here.

We'll want some sort of large-scale integration test before dropping the old template class though, so we know if it breaks something.

**Comment by jakevdp** [comment]
Also, I was just looking through the PseudoPolynomial class – that's really nice! Great code design on that one.

**Comment by johnh2o2** [comment]
@jakevdp -- glad that ones a bit easier! Though, I think the `PseudoPolynomial` class is doing more work than it has to; it can handle all instances that fit the form

`(1 - x^2)^(r) * (p(x) + sqrt(1 - x^2)*q(x))`

though in doing so it ends up increasing the order of the zero finding polynomial by +2 for the specific case used in the fast template periodogram:

```
[ p_1(x) + sqrt(1- x^2)q_1(x) ]*[ p_2(x) + sqrt(1- x^2)q_2(x) ]*[ p_3(x) + q_3(x) / sqrt(1 - x^2) ]
```

If you expand this by hand, at some point squaring to get rid of `sqrt(1 - x^2)`, you get a zero-finding polynomial with order `6H`. However, if you do it, forcing all polynomials to be in the form

```
(1 - x^2)^r * (p(x) + sqrt(1 - x^2)q(x)
```

you get a zero finding polynomial of order `6H + 2`. Which slows things down (not sure how much exactly). I'm not sure how to elegantly fix that problem.

**Comment by jakevdp** [comment]
Hmm... I'll put some thought into that.

**Comment by johnh2o2** [comment]
Not too crucial at this point -- I don't suspect it's a bottleneck, but I would guess that fixing this will make a small but noticeable difference (maybe ~5-10%?) in the current implementation. If you find ways to speed up computing the coefficients, then this will become more important. The last time I checked, the root-finding step took about the same amount of time as computing the coefficients.

**Comment by jakevdp** [comment]
I wonder if sympy's symbolic manipulation of these kinds of expressions would be smarter?

**Comment by johnh2o2** [comment]
That's an idea I've explored in the past, but I wasn't able to come up with any shortcuts. I was hoping that SymPy would help convert the polynomial algebra into an explicit expression for the coefficients, but wasn't able to accomplish that in a reasonable amount of time. I'm not a SymPy expert, so it might be worth revisiting.

**Pull request merged**
